### ISSUE TITLE
After translating the Error page into Chinese, it only redirects to the homepage Chinese page.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Modern-Education-Student-Exchange-Services#142]

**Comment by Santosh-titan** [comment]
You can't directly translate this because its not a page it is a template (404.php).
If you want to test 404 error for chinese follow this steps
1. Select chinese language then try to access any non existing page like this
http://www.meses.dev/sddfgldfhdf/?lang=zh-hans

404 page for English
http://www.meses.dev/sddfgldfhdf

I hope you understand

Thanks
